version: 3
services:
  cms:
    build:
      context: .
      target: cms
    environment:
      PREVIEW_URL: http://localhost:3001/
    volumes:
      - ./_db.git:/website.git:z
    ports:
      - 3000:3000
    userns_mode: keep-id:uid=1000,gid=1000
  checkout:
    build:
      context: .
      target: checkout
    environment:
      BRANCH: master
    volumes:
      - ./_db.git:/website.git:z
      - preview_checkout:/checkout
    userns_mode: keep-id:uid=1000,gid=1000
  preview:
    build:
      context: .
      target: preview
    volumes:
      - preview_checkout:/checkout
    ports:
      - 3001:3001
    userns_mode: keep-id:uid=1000,gid=1000
  build-www:
    build:
      context: .
      target: build-www
    environment:
      BRANCH: master
    volumes:
      - ./_db.git:/website.git:z
      - www:/www
    userns_mode: keep-id:uid=1000,gid=1000
  caddy:
    image: docker.io/caddy
    ports:
      - "3002:80/tcp"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - www:/usr/share/caddy
volumes:
  caddy_data:
  caddy_config:
  www:
  preview_checkout:
